name: Release Build

on:
  release:
    types: [created]

jobs:
  build:
    name: Build CLI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # Change this if needed

      - name: Install dependencies
        run: go mod tidy

      - name: Build for multiple platforms (amd64 & arm64)
        run: |
          mkdir -p dist

          # Linux
          GOOS=linux GOARCH=amd64 go build -o dist/livediff-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o dist/livediff-linux-arm64 .

          # macOS (Darwin)
          GOOS=darwin GOARCH=amd64 go build -o dist/livediff-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o dist/livediff-darwin-arm64 .

          # Windows
          GOOS=windows GOARCH=amd64 go build -o dist/livediff-windows-amd64.exe .
          GOOS=windows GOARCH=arm64 go build -o dist/livediff-windows-arm64.exe .

      - name: Upload artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
